;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Backyard.Interaction.Use",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Pickup",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Interact",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Disassemble",DevComment="")
+GameplayTagList=(Tag="Backyard.Tool.Saw",DevComment="")
+GameplayTagList=(Tag="Backyard.Tool.Wrench",DevComment="")
+GameplayTagList=(Tag="Backyard.Item.Sentry",DevComment="")
+GameplayTagList=(Tag="Backyard.Item.Resource",DevComment="")

