;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Backyard.Capability.Aim",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Ammo",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Detection",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Detection.Optical",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Detection.Radar",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Detection.Thermal",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Fire",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Lidar",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Power",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Power.Source",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Power.Storage",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Power.Tap",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.PowerStorage",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Rangefinder",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.Shield",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.TargetRecognition",DevComment="")
+GameplayTagList=(Tag="Backyard.Capability.ThermalVision",DevComment="")
+GameplayTagList=(Tag="Backyard.Counter.Chaff",DevComment="")
+GameplayTagList=(Tag="Backyard.Counter.Cloak",DevComment="")
+GameplayTagList=(Tag="Backyard.Counter.Smoke",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Disassemble",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Interact",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Pickup",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Terminal",DevComment="")
+GameplayTagList=(Tag="Backyard.Interaction.Use",DevComment="")
+GameplayTagList=(Tag="Backyard.Item.Resource",DevComment="")
+GameplayTagList=(Tag="Backyard.Item.Sentry",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Battery",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Chassis",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Detector",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Frame",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Magazine",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.PSU",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Shield",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Turret",DevComment="")
+GameplayTagList=(Tag="Backyard.Module.Weapon",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Battery",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Detector",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Magazine",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.PSU",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Shield",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Turret",DevComment="")
+GameplayTagList=(Tag="Backyard.Slot.Utility",DevComment="")
+GameplayTagList=(Tag="Backyard.State.Damaged",DevComment="")
+GameplayTagList=(Tag="Backyard.State.Dragging",DevComment="")
+GameplayTagList=(Tag="Backyard.State.Jammed",DevComment="")
+GameplayTagList=(Tag="Backyard.State.Powered",DevComment="")
+GameplayTagList=(Tag="Backyard.State.Starved",DevComment="")
+GameplayTagList=(Tag="Backyard.Target.Friendly",DevComment="")
+GameplayTagList=(Tag="Backyard.Target.Hostile",DevComment="")
+GameplayTagList=(Tag="Backyard.Target.Misc",DevComment="")
+GameplayTagList=(Tag="Backyard.Tool.Multimeter",DevComment="")
+GameplayTagList=(Tag="Backyard.Tool.Saw",DevComment="")
+GameplayTagList=(Tag="Backyard.Tool.Wrench",DevComment="")

